
export const FETCH_HISTORIC_DATA = 'FETCH_HISTORIC_DATA';
export const FETCH_HISTORIC_DATA_SUCCESS = 'FETCH_HISTORIC_DATA_SUCCESS';
export const FETCH_HISTORIC_DATA_PENDING = 'FETCH_HISTORIC_DATA_PENDING';
export const FETCH_HISTORIC_DATA_FAIL = 'FETCH_HISTORIC_DATA_FAIL';
export const SAVE_VOLUME = 'SAVE_VOLUME';

